from typing import Protocol

from openai import OpenAI, OpenAIError

from app.config import get_openai_api_key, get_tts_model, get_tts_voice


class SpeechGenerationError(Exception):
    """Speech could not be generated by the external provider."""


class SpeechService(Protocol):
    def generate(self, text: str) -> bytes: ...


class OpenAISpeechService:
    def generate(self, text: str) -> bytes:
        # Disable automatic retries: a retry could generate and bill the same line twice.
        api_key = get_openai_api_key()
        try:
            with OpenAI(api_key=api_key, timeout=30.0, max_retries=0) as client:
                response = client.audio.speech.create(
                    model=get_tts_model(),
                    voice=get_tts_voice(),
                    input=text,
                    response_format="mp3",
                )
                audio = response.content
        except OpenAIError as error:
            raise SpeechGenerationError() from error
        if not audio:
            raise SpeechGenerationError()
        return audio


def get_speech_service() -> SpeechService:
    return OpenAISpeechService()
