from typing import Protocol
import logging

from openai import APIConnectionError, OpenAI, OpenAIError

from app.config import TTS_READER_INSTRUCTIONS, get_character_voice, get_openai_api_key, get_tts_model
from app.services.audio import trim_silent_tail


logger = logging.getLogger(__name__)


class SpeechGenerationError(Exception):
    """Speech could not be generated by the external provider."""

    def __init__(self, message: str = "Speech generation failed", *, retryable: bool = False):
        super().__init__(message)
        self.retryable = retryable


class SpeechService(Protocol):
    def generate(self, text: str, voice_index: int = 0) -> bytes: ...


class OpenAISpeechService:
    def generate(self, text: str, voice_index: int = 0) -> bytes:
        # Disable automatic retries: a retry could generate and bill the same line twice.
        api_key = get_openai_api_key()
        voice = get_character_voice(voice_index)
        try:
            with OpenAI(api_key=api_key, timeout=30.0, max_retries=0) as client:
                response = client.audio.speech.create(
                    model=get_tts_model(),
                    voice=voice,
                    input=text,
                    instructions=TTS_READER_INSTRUCTIONS,
                    response_format="wav",
                )
                audio = response.content
        except OpenAIError as error:
            status_code = getattr(error, "status_code", None)
            code = getattr(error, "code", None)
            retryable = isinstance(error, APIConnectionError) or (
                status_code in (408, 409, 429) or (status_code is not None and status_code >= 500)
            )
            if code in ("insufficient_quota", "billing_hard_limit_reached"):
                retryable = False
            # Metadata only: never log dialogue, API keys, or provider response bodies.
            logger.warning(
                "Speech provider failure: type=%s status=%s code=%s request_id=%s retryable=%s",
                type(error).__name__, status_code, code, getattr(error, "request_id", None), retryable,
            )
            raise SpeechGenerationError(retryable=retryable) from error
        if not audio:
            logger.warning("Speech provider returned empty audio")
            raise SpeechGenerationError(retryable=True)
        return trim_silent_tail(audio)


def get_speech_service() -> SpeechService:
    return OpenAISpeechService()
